package org.pjdbc.rmi;

import java.io.*;
import java.math.*;
import java.rmi.*;
import java.sql.*;
import java.util.*;

public interface PreparedStatementHandler extends StatementHandler, Remote {
    void addBatch () throws RemoteException;
    void clearParameters () throws RemoteException;
    boolean execute () throws RemoteException;
    long executeLargeUpdate () throws RemoteException;
    ResultSet executeQuery () throws RemoteException;
    int executeUpdate () throws RemoteException;
    ResultSetMetaData getMetaData () throws RemoteException;
    ParameterMetaData getParameterMetaData () throws RemoteException;
    void setArray (int parameterIndex, Array x) throws RemoteException;
    void setAsciiStream (int parameterIndex, InputStream x, int length) throws RemoteException;
    void setAsciiStream (int parameterIndex, InputStream x, long length) throws RemoteException;
    void setBigDecimal (int parameterIndex, BigDecimal x) throws RemoteException;
    void setBinaryStream (int parameterIndex, InputStream x) throws RemoteException;
    void setBinaryStream (int parameterIndex, InputStream x, int length) throws RemoteException;
    void setBinaryStream (int parameterIndex, InputStream x, long length) throws RemoteException;
    void setBlob (int parameterIndex, Blob x) throws RemoteException;
    void setBlob (int parameterIndex, InputStream inputStream) throws RemoteException;
    void setBlob (int parameterIndex, InputStream inputStream, long length) throws RemoteException;
    void setBoolean (int parameterIndex, boolean x) throws RemoteException;
    void setByte (int parameterIndex, byte x) throws RemoteException;
    void setBytes (int parameterIndex, byte[] x) throws RemoteException;
    void setCharacterStream (int parameterIndex, Reader reader) throws RemoteException;
    void setCharacterStream (int parameterIndex, Reader reader, int length) throws RemoteException;
    void setCharacterStream (int parameterIndex, Reader reader, long length) throws RemoteException;
    void setClob (int parameterIndex, Clob x) throws RemoteException;
    void setClob (int parameterIndex, Reader reader) throws RemoteException;
    void setClob (int parameterIndex, Reader reader, long length) throws RemoteException;
    void setDate (int parameterIndex, java.sql.Date x) throws RemoteException;
    void setDate (int parameterIndex, java.sql.Date x, Calendar cal) throws RemoteException;
    void setDouble (int parameterIndex, double x) throws RemoteException;
    void setFloat (int parameterIndex, float x) throws RemoteException;
    void setInt (int parameterIndex, int x) throws RemoteException;
    void setLong (int parameterIndex, long x) throws RemoteException;
    void setNCharacterStream (int parameterIndex, Reader value) throws RemoteException;
    void setNCharacterStream (int parameterIndex, Reader value, long length) throws RemoteException;
    void setNClob (int parameterIndex, NClob value) throws RemoteException;
    void setNClob (int parameterIndex, Reader reader) throws RemoteException;
    void setNClob (int parameterIndex, Reader reader, long length) throws RemoteException;
    void setNString (int parameterIndex, String value) throws RemoteException;
    void setNull (int parameterIndex, int sqlType) throws RemoteException;
    void setNull (int parameterIndex, int sqlType, String typeName) throws RemoteException;
    void setObject (int parameterIndex, Object x) throws RemoteException;
    void setObject (int parameterIndex, Object x, int targetSqlType) throws RemoteException;
    void setObject (int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws RemoteException;
    void setRef (int parameterIndex, Ref x) throws RemoteException;
    void setRowId (int parameterIndex, RowId x) throws RemoteException;
    void setShort (int parameterIndex, short x) throws RemoteException;
    void setSQLXML (int parameterIndex, SQLXML xmlObject) throws RemoteException;
    void setString (int parameterIndex, String x) throws RemoteException;
    void setTime (int parameterIndex, Time x) throws RemoteException;
    void setTime (int parameterIndex, Time x, Calendar cal) throws RemoteException;
    void setTimestamp (int parameterIndex, Timestamp x) throws RemoteException;
    void setTimestamp (int parameterIndex, Timestamp x, Calendar cal) throws RemoteException;
    void setUnicodeStream (int parameterIndex, InputStream x, int length) throws RemoteException;}
